export const dashboard = <i className="fa-solid fa-house"></i>
export const Transactions = <i className="fa-solid fa-credit-card"></i>
export const incomes = <i className="fa-solid fa-money-bill-trend-up"></i>
export const expense = <i className="fa-solid fa-money-bill"></i>
export const user = <i className="fa-solid fa-user-tie"></i>
export const signOut = <i className="fa-solid fa-arrow-right-from-bracket"></i>
export const salary = <i className="fa-solid fa-money-bill"></i>
export const freelancing = <i className="fa-solid fa-earth-asia"></i>
export const investments = <i className="fa-solid fa-vault"></i>
export const stocks = <i className="fa-solid fa-money-bill-trend-up"></i>
export const bitcoin = <i className="fa-brands fa-bitcoin"></i>
export const banktransfer = <i className="fa-solid fa-building-columns"></i>
export const youtube = <i className="fa-brands fa-youtube"></i>
export const other = <i className="fa-brands fa-squarespace"></i>
export const Delete = <i className="fa-solid fa-trash"></i>